# Generated by Django 4.2.5 on 2023-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="organizations",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="offices",
        ),
        migrations.AddField(
            model_name="customer",
            name="organizations",
            field=models.ManyToManyField(to="organization.organization"),
        ),
        migrations.AddField(
            model_name="organization",
            name="offices",
            field=models.ManyToManyField(to="organization.office"),
        ),
    ]
